test failure
Signed-off-by: Sunny Yip <sunny@kusari.dev>

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -19,6 +19,11 @@ inputs:
     description: 'Release version of guacsec/guac to use to source the guac cli'
     required: false
     default: 'v0.5.2'
+  simulate-failure:
+    description: 'Whether to force the action to fail to simulate a failure case'
+    type: boolean
+    required: false
+    default: false
 # outputs:
 #   console_out:
 #     description: 'raw console output from guacone command'
@@ -27,6 +32,13 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: simulate failure 
+      if: ${{ inputs.similate-failure }}
+      shell: bash
+      run: |
+        echo "Failing deliberately..."
+        exit 1
+
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
